### ISSUE TITLE
PTP support when using CRD

### ISSUE THREAD

**Issue by egernst** [Intel-Corp/multus-cni#30]
Steps:

1. Copy multus configration file to /etc/cni/net.d/:
```
{
    "type": "multus",
    "log_level": "debug",
    "kubeconfig": "/etc/kubernetes/admin.conf",
    "delegates": [{
        "name": "flannel",
        "type": "flannel",
        "masterplugin": true
    } ]
}
```

2. Start a single node kubernetes cluster:
```sudo -E kubeadm init --pod-network-cidr 10.244.0.0/16```

3. Startup flannel, using .yamls from the upstream coreOS repo:
```
sudo -E kubectl create -f "../k8s/kube-flannel-rbac.yml"
sudo -E kubectl create --namespace kube-system -f "../k8s/kube-flannel.yml"
```

4. Taint master so we can schedule work on it and create a custom resource definition for networks:
```
master=$(hostname)
sudo -E kubectl taint nodes "$master" node-role.kubernetes.io/master:NoSchedule-
kubectl create -f crd-network.yaml
``` 
Where crd-network yaml is:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: networks.kubernetes.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kubernetes.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: networks
    # singular name to be used as an alias on the CLI and for display
    singular: network
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Network
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - net
```

5.  Create a few CRD network types on the system, based on following yaml:
```
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: ptp-net
plugin: ptp
args: '[
    {
        "name": "ptp-net",
        "type": "ptp",
        "ipam": {
                  "type": "host-local",
                  "subnet": "10.248.246.144/28",
                  "routes": [
                   { "dst": "0.0.0.0/0" }
        }
    }
]'

---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: br-net-1
plugin: bridge
args: '[
    {
        "name": "br-net-1",
        "type": "bridge",
        "bridge": "br-net-1",
        "ipam": {
            "type": "host-local",
            "subnet": "10.1.10.0/24"
        }
    }
]'

---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: br-net-2
plugin: bridge
args: '[
    {
        "name": "br-net-2",
        "type": "bridge",
        "bridge": "br-net-2",
        "ipam": {
            "type": "host-local",
            "subnet": "11.1.1.0/24"
        }
    }
]'
```

6.  Start a pod making use of each of these three networks:

```
$ sudo -E kubectl create -f ptp-pod.yaml
$ cat ptp-pod.yaml 
---
apiVersion: v1
kind: Pod # TODO make these deployments later
metadata:
  name: ptp-test
  annotations:
    networks: '[
        { "name": "br-net-1" },
        { "name": "br-net-2" },
        { "name": "ptp-net" }
    ]'
spec:
  containers:
  - name: ptp-test
    image: "ubuntu:14.04"
    command: ["top"]
    stdin: true
    tty: true
```

7.  See following networks:

```
$ sudo -E kubectl exec -it ptp-test  -- bash
root@ptp-test:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if135: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 0a:58:0a:f4:00:44 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.68/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5433:ff:fe5f:9145/64 scope link 
       valid_lft forever preferred_lft forever
```

8.  Bring up one more pod, this time not using PTP:

```
sudo -E kubectl create -f test-pod.yaml 
 cat test-pod.yaml 
---
apiVersion: v1
kind: Pod # TODO make these deployments later
metadata:
  name: no-ptp-test
  annotations:
    networks: '[
        { "name": "br-net-1" },
        { "name": "br-net-2" }
    ]'
spec:
  containers:
  - name: no-ptp-test
    image: "ubuntu:14.04"
    stdin: true
    tty: true
```

9. Network comes up without issue:
```
$ sudo -E kubectl exec -it no-ptp-test2 -- bash -c "ip a"
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if146: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 0a:58:0a:01:0a:03 brd ff:ff:ff:ff:ff:ff
    inet 10.1.10.3/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8c3e:a1ff:fed1:8659/64 scope link 
       valid_lft forever preferred_lft forever
5: net0@if147: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 0a:58:0b:01:01:03 brd ff:ff:ff:ff:ff:ff
    inet 11.1.1.3/24 scope global net0
       valid_lft forever preferred_lft forever
    inet6 fe80::2098:afff:febf:fbb0/64 scope link 
       valid_lft forever preferred_lft forever
```
