### ISSUE TITLE
Cannot make my TPR Network objects to work.

### ISSUE THREAD

**Issue by Machi029** [Intel-Corp/multus-cni#31]
**Environment:**
Kubernetes 1.7.3
**Issue**
I think I've configured my environment correctly... but cannot get TPR Network objects to work.
Here is the yaml file for deploying my pod.

```
apiVersion: v1
kind: Pod
metadata:
  name: multus-multi-net-poc
  annotations:
    networks: '[
        { "name": "multus-calico" },
        { "name": "macvlan-conf" }
    ]'
spec:  # specification of the pod's contents
  containers:
  - name: multus-multi-net-poc
    image: "busybox"
    command: ["top"]
    stdin: true
    tty: true
```

If I deploy it, it only comes up only with one NIC which I want multiple nics.

```
root@cam1:~# kubectl create -f pod-multi-network.yaml
pod "multus-multi-net-poc" created
root@cam1:~# kubectl exec -it multus-multi-net-poc ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if137: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether f2:3f:c8:49:9d:fe brd ff:ff:ff:ff:ff:ff
    inet 10.1.188.11/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f03f:c8ff:fe49:9dfe/64 scope link
       valid_lft forever preferred_lft forever
```
**Steps I did for configuration**

1. installed golang 1.8 and build Multus and CNI Plugins(for macvlan adn host-local)

```
# dpkg -i golang-1.8-src_1.8.5-1ubuntu1~longsleep1+xenial_amd64.deb golang-1.8-go_1.8.5-1ubuntu1~longsleep1+xenial_amd64.deb
# export PATH=/usr/lib/go-1.8/bin/:${PATH}
# unzip multus-cni-master.zip
# cd multus-cni-master/
# ./build
# cp bin/multus /opt/cni/bin/
# unzip plugins-master.zip
# cd plugins-master/
# ./build
# cp bin/macvlan /opt/cni/bin/
# cp bin/host-local /opt/cni/bin/
```

2. created /etc/cni/net.d/10-a-multus-cni.conf

```
{
    "delegates": [
        {
            "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
            "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
            "etcd_endpoints": "https://...:4001",
            "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
            "hairpinMode": true,
            "ipam": {
                "type": "calico-ipam"
            },
            "kubernetes": {
                "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
            },
            "log_level": "info",
            "masterplugin": true,
            "name": "multus-calico",
            "policy": {
                "k8s_api_root": "https://10.0.0.1:443",
                "k8s_auth_token": "...",
                "type": "k8s"
            },
            "type": "calico"
        }
    ],
    "name": "minion1-multus-demo-network",
    "type": "multus"
}
```

3. Restart all nodes

`# systemctl restart kubelet`

4. Create CRD

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: networks.kubernetes.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kubernetes.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: networks
    # singular name to be used as an alias on the CLI and for display
    singular: network
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Network
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - net
```

```
# kubectl create -f crdnetwork.yaml
# kubectl get CustomResourceDefinition
NAME                      KIND
networks.kubernetes.com   CustomResourceDefinition.v1beta1.apiextensions.k8s.io
```

5 Create TPR
```
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: network.kubernetes.com
description: "A specification of a Network obj in the kubernetes"
versions:
- name: v1
```

```
root@cam1:~# kubectl create -f ./tprnetwork.yaml
thirdpartyresource "network.kubernetes.com" created
root@cam1:~# kubectl get thirdpartyresource
NAME                     DESCRIPTION                                          VERSION(S)
network.kubernetes.com   A specification of a Network obj in the kubernetes   v1
```

6. Create Network

```
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: macvlan-conf
plugin: macvlan
args: '[
        {
            "ipam": {
                "ranges": [
                    [
                        {
                            "subnet": "1.1.1.0/24"
                        }
                    ]
                ],
                "type": "host-local"
            },
            "master": "eth0",
            "name": "macvlan-conf",
            "type": "macvlan"
        }
]'
```

```
# kubectl create -f macvlan.yaml
network "macvlan-conf" created
# kubectl get networks
NAME           KIND
macvlan-conf   Network.v1.kubernetes.com
# kubectl get network macvlan-conf -o yaml
apiVersion: kubernetes.com/v1
args: '[ { "ipam": { "ranges": [ [ { "subnet": "1.1.1.0/24" } ] ], "type": "host-local"
  }, "master": "eth0", "name": "macvlan-conf", "type": "macvlan" } ]'
kind: Network
metadata:
  creationTimestamp: 2017-12-01T01:57:02Z
  name: macvlan-conf
  namespace: default
  resourceVersion: "377220"
  selfLink: /apis/kubernetes.com/v1/namespaces/default/networks/macvlan-conf
  uid: ec7394db-d63a-11e7-b5e6-fa163e90ea75
plugin: macvlan
```

**By the way**

This multus config worked (which is just adding the macvlan config directly to the file) so I do believe I have my infrastructure correct.

```
{
    "delegates": [
        {
            "ipam": {
                "ranges": [
                    [
                        {
                            "subnet": "1.1.1.0/24"
                        }
                    ]
                ],
                "type": "host-local"
            },
            "master": "eth0",
            "name": "macvlan-conf",
            "type": "macvlan"
        },
        {
            "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
            "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
            "etcd_endpoints": "https://...:4001",
            "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
            "hairpinMode": true,
            "ipam": {
                "type": "calico-ipam"
            },
            "kubernetes": {
                "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
            },
            "log_level": "info",
            "masterplugin": true,
            "name": "multus-calico",
            "policy": {
                "k8s_api_root": "https://10.0.0.1:443",
                "k8s_auth_token": "...",
                "type": "k8s"
            },
            "type": "calico"
        }
    ],
    "name": "minion1-multus-demo-network",
    "type": "multus"
}
```

```
root@cam1:~# kubectl exec -it multus-multi-net-poc-2 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if232: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether 52:85:d7:e4:1c:f4 brd ff:ff:ff:ff:ff:ff
    inet 10.1.183.49/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5085:d7ff:fee4:1cf4/64 scope link
       valid_lft forever preferred_lft forever
5: net0@tunl0: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether 42:65:98:0f:2c:7a brd ff:ff:ff:ff:ff:ff
    inet 1.1.1.2/24 scope global net0
       valid_lft forever preferred_lft forever
    inet6 fe80::4065:98ff:fe0f:2c7a/64 scope link
       valid_lft forever preferred_lft forever
root@cam1:~#
```

However I trully want to use the TPR function instead...
