### ISSUE TITLE
networks annotations not working in version 1.8.0-00

### ISSUE THREAD

**Issue by sheetaljoshi** [Intel-Corp/multus-cni#46]
I am running kubeadm version 1.8.0-00. And default network is multus-flannel 10-multus-flannel.conf
```json
{
  "name": "multus-demo",
  "type": "multus",
  "delegates": [
    {
      "type": "flannel",
      "masterplugin": true,
      "delegate": {
        "isDefaultGateway": true
      }
    }
  ]
}
```
I created CustomResourceDefinition as below
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.kubernetes.com
spec:
  group: kubernetes.com
  version: v1
  scope: Namespaced
  names:
    plural: networks
    singular: network
    kind: Network
    shortNames:
    - net
```
And my other network is local bridge
```yaml
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: bridge-conf
plugin: bridge
args: '[
    {
      "type": "bridge",
      "name": "lanbr",
      "bridge": "lanbr",
      "isGateway": true,
      "ipMasq": true,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.122.0/24",
        "rangeStart": "192.168.122.200",
        "rangeEnd": "192.168.122.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.122.1"
     }
    },
]'
```

And when I tried to create multi-network-pod as below
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: multus-multi-net-poc
  annotations:
    networks: '[
        { "name": "bridge-conf" }
    ]'
spec: 
  containers:
  - name: multus-multi-net-poc
    image: "busybox"
    command: ["top"]
    stdin: true
    tty: true
```
I only see flannel network eth0 inside the pod and bridge network not being added. And I also notice that no bridges are created on host either (lanbr). Can you please suggest if I am missing something.

And when I tried to create multus-network using [this yaml](https://github.com/Intel-Corp/multus-cni/files/1767862/kube-multus-file.txt) I could see both networks and interfaces added inside the pod. But annotations doesn't work for me.

**Comment by derwin4o** [comment]
Hi @sheetaljoshi , please see issue #42  I had the same problem and crd permissions per node , solved the issue. 
Regards!

**Comment by sheetaljoshi** [comment]
So these are the steps I followed (my hostname is master and I have single node cluster for now)

```console
root@master:~# uname -a
Linux master 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```sh
kubeadm init --pod-network-cidr=10.244.0.0/16 && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config && kubectl taint nodes --all node-role.kubernetes.io/master-
```

My /etc/cni/net.d/10-multus.conf looks as below
```json
{
  "name": "multus-cni-network",
  "type": "multus",
  "kubeconfig": "/etc/kubernetes/kubelet.conf"
}
```

And my crd definition 
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: networks.kubernetes.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kubernetes.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: networks
    # singular name to be used as an alias on the CLI and for display
    singular: network
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Network
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - net
```

Cluster role definition
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multus-crd-overpowered
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

And I create clusterrolebidning as 
```sh
kubectl create clusterrolebinding multus-node-master --clusterrole=multus-crd-overpowered --user=system:node:master
```
flannel.yaml looks like below
```yaml
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: flannel-conf
plugin: flannel
args: '[
        {
                "delegate": {
                        "isDefaultGateway": true,
                        "masterplugin": true
                }
        }
]'
```

adn macvlan conf looks like
```yaml
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: macvlan-conf
plugin: macvlan
args: '[
        {
            "master": "eth0",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                        "subnet": "10.56.217.0/24",
                        "rangeStart": "10.56.217.171",
                        "rangeEnd": "10.56.217.181",
                        "routes": [
                                { "dst": "0.0.0.0/0" }
                        ],
                        "gateway": "10.56.217.1"
                }
        }
]'
```

And after I create above networks I restart my kubelet

But I still see kubedns in containercreating state. 
And error as 

Mar  1 18:58:04 master kubelet[4653]: E0301 18:58:04.585318    4653 kuberuntime_manager.go:580] killPodWithSyncResult failed: failed to "KillPodSandbox" for "96a7de35-1d81-11e8-b239-000c296d7407" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"kube-dns-6f4fd4bdf-4m7pf_kube-system\" network: Multus: Err in getting k8s network from pod: no kubernetes network found"
