### ISSUE TITLE
Macvlan and flannel issue. 

### ISSUE THREAD

**Issue by burnyd** [Intel-Corp/multus-cni#50]
Kub version 1.10
OS: Ubuntu 16.04.4 LTS

Hi, I am able to follow the readme on getting flannel to work just fine.  I however am trying to work with macvlan for certain pods that have more of a nfv type issue where they need to bridge to a physical interface.  My end goal would be able to select some pods that would run with bridged interfaces and some that would simply just use flannel interfaces.  So the network type currently looks like the following..

```
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: macvlan-conf
plugin: macvlan 
args: '[
{
                  "type": "macvlan",
                  "master": "ens160",
                  "mode": "bridge",
                  "ipam": {
                          "type": "host-local",
                          "subnet": "10.20.30.0/24",
                          "rangeStart": "10.20.30.200",
                          "rangeEnd": "10.20.30.205"
                          "routes": [
              { "dst": "0.0.0.0/0" }
            ],
            "gateway": "10.20.30.250"
         }
    }
]'
```

Here is an example pod that will only pull a interface from Flannel and not from macvlan.  I am sure it is something small I am doing wrong?

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-multus
  annotations:
    networks: '[  
        { "name": "flannel-conf" },
        { "name": "macvlan-conf" }
    ]'
  labels:
    type: ubuntu
    vendor: Canonical
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  nodeSelector:
    multusselector: "yes"
```
