### ISSUE TITLE
Mismatch between the Self Link in apiserver - K8s plumbing working group documentation and the implementation

### ISSUE THREAD

**Issue by rkamudhan** [Intel-Corp/multus-cni#56]
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.kubernetes.cni.cncf.io
spec:
  group: kubernetes.cni.cncf.io
  version: v1
  scope: Namespaced
  names:
	plural: networks
	singular: network
	kind: Network
	shortNames:
	- net
```
Implementation: https://github.com/Intel-Corp/multus-cni/blob/122dbfb345ae4a13fd1d592723a0ba1603278dd9/multus/multus.go#L386
