### ISSUE TITLE
Mismatch between the network annotation in  - K8s plumbing working group documentation and the implementation

### ISSUE THREAD

**Issue by rkamudhan** [Intel-Corp/multus-cni#57]
```
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
  annotations:
    kubernetes.v1.cni.cncf.io/networks:  netA,netB,other-ns/netC
```
Implementation: https://github.com/Intel-Corp/multus-cni/blob/122dbfb345ae4a13fd1d592723a0ba1603278dd9/multus/multus.go#L278

**Comment by rkamudhan** [comment]
@dougbtv @s1061123 : I think, we have to change the documentation for it.

**Comment by dougbtv** [comment]
Yep, this is definitely a mistake here, I don't think the version string got attached. Here's the sample pod I was working from:

```
apiVersion: v1
kind: Pod
metadata:
  name: bothpod
  annotations:
    kubernetes.cni.cncf.io/networks: macvlan-conf,flannel-conf
spec:
  containers:
  - name: bothpod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
```

And that pod really needs to be...

```
apiVersion: v1
kind: Pod
metadata:
  name: bothpod
  annotations:
    kubernetes.v1.cni.cncf.io/networks: macvlan-conf,flannel-conf
spec:
  containers:
  - name: bothpod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
```

I'll submit a fix for this one -- thanks for the eyes Kural! (I also left a [comment](https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/edit?disco=AAAAB3eqX6c) on the spec in response to yours, too.
